### ISSUE TITLE
sporadic precompile failures on heroku

### ISSUE THREAD

**Issue by ghost** [botandrose/sprockets-image_compressor#12]
I'm getting sporadic failures precompiling on heroku with this gem.  You can see one below.  Anyone else seen this?  Is it some sort of filesystem issue on heroku?

```
   I, [2014-03-06T22:27:31.214690 #888]  INFO -- : Writing /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/public/assets/icons/right-arrow-f4b92e0eb8fb3b6d72e85e8ff14f7a42.png
   rake aborted!
   No such file or directory @ rb_sysopen - /tmp/in_file20140306-888-n5rzjl.png.optimized.png
   (in /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/app/assets/images/icons/star-no.png)
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/png_compressor.rb:20:in `initialize'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/png_compressor.rb:20:in `open'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/png_compressor.rb:20:in `block in compress'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/png_compressor.rb:12:in `compress'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/integration.rb:9:in `block in setup'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-2.10.1/lib/sprockets/processor.rb:29:in `call'
```

**Comment by botandrose** [comment]
Hmm, yeah, seems like heroku has changed something with how their filesystem works in the last year or so. I don't use heroku anymore, so I'm not really able to debug this. Let me know what you find!
