### ISSUE TITLE
Can't modify immutable index

### ISSUE THREAD

**Issue by cheeyeo** [botandrose/sprockets-image_compressor#9]
Using the master branch of sprockets_image_compressor inside gemfile of a rails 3.2.13 app , ran bundle and then the asset compilation task for production i get the following errors:

```
RAILS_ENV=production bundle exec rake assets:precompile 

/Users/chee/.rvm/rubies/ruby-1.9.3-p429/bin/ruby /Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets

rake aborted!
can't modify immutable index

/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/sprockets-2.2.2/lib/sprockets/index.rb:80:in `expire_index!'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/sprockets-2.2.2/lib/sprockets/processing.rb:15:in `register_mime_type'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/bundler/gems/sprockets-image_compressor-cb5beaa1a5a5/lib/sprockets/image_compressor/integration.rb:7:in `setup'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/bundler/gems/sprockets-image_compressor-cb5beaa1a5a5/lib/sprockets/image_compressor/railtie.rb:5:in `block in <class:Railtie>'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/chee/rails3apps/fokpversion2/config/environment.rb:5:in `<top (required)>'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/railties-3.2.13/lib/rails/application.rb:103:in `require_environment!'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/railties-3.2.13/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/actionpack-3.2.13/lib/sprockets/assets.rake:93:in `block (2 levels) in <top (required)>'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/actionpack-3.2.13/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
Tasks: TOP => environment
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/Users/chee/.rvm/rubies/ruby-1.9.3-p429/bi...]
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/actionpack-3.2.13/lib/sprockets/assets.rake:12:in `ruby_rake_task'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/actionpack-3.2.13/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/gems/actionpack-3.2.13/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/bin/ruby_noexec_wrapper:14:in `eval'
/Users/chee/.rvm/gems/ruby-1.9.3-p429@fokp/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

```

**Comment by cheeyeo** [comment]
The app is running on rails 3.2.13 and ruby 1.9.3p429

**Comment by botandrose** [comment]
Can you post a minimal app that I can clone to reproduce?
